views:
  - id:
      id: events
      type: modelList
    title: Events
    menuItem:
      title: All Events
      svgSrc: assets/icons/menu_doc.svg
      group: event-system
    layouts:
      defaultList:
        type: modelList
        fieldCombos:
          - "state"
          - "title\nslug"
          - "starts"
          - "ends"
          - "[locationName](locationURL)"
  - id:
      id: events
      type: modelCreate
    title: Create a new event
    menuItem:
      title: Create Event
      svgSrc: assets/icons/menu_doc.svg
      group: event-system
menuGroups:
  event-system:
    title: Event System
    description: Manage events & subscriptions